#!/usr/bin/env bash
# setup-ios-config.sh
#
# Generates ios/doit/Config/Local.xcconfig from environment variables.
# Run this before opening the Xcode project so the app points to the right
# Supabase project.
#
# Usage:
#   export DOIT_SUPABASE_URL=https://<ref>.supabase.co
#   export DOIT_SUPABASE_ANON_KEY=<your_anon_key>
#   ./scripts/setup-ios-config.sh
#
# If env vars are not set, the script copies from Local.example.xcconfig
# and shows instructions.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
CONFIG_DIR="$PROJECT_DIR/ios/doit/Config"
LOCAL_CONFIG="$CONFIG_DIR/Local.xcconfig"
EXAMPLE_CONFIG="$CONFIG_DIR/Local.example.xcconfig"

SUPABASE_URL="${DOIT_SUPABASE_URL:-}"
ANON_KEY="${DOIT_SUPABASE_ANON_KEY:-}"
WAITLIST_URL="${DOIT_WAITLIST_URL:-}"
BYO_ENABLED="${DOIT_BYO_CONNECTOR_ENABLED:-true}"

if [ -n "$SUPABASE_URL" ] && [ -n "$ANON_KEY" ]; then
    cat > "$LOCAL_CONFIG" <<EOF
// Auto-generated by setup-ios-config.sh
// DO NOT COMMIT — this file is gitignored.

DOIT_SUPABASE_URL = $SUPABASE_URL
DOIT_SUPABASE_ANON_KEY = $ANON_KEY
DOIT_WAITLIST_URL = ${WAITLIST_URL:-https://example.com/waitlist}
DOIT_BYO_CONNECTOR_ENABLED = $BYO_ENABLED

DOIT_DEVELOPMENT_TEAM = YOUR_APPLE_TEAM_ID
DOIT_BUNDLE_ID = com.yourorg.doit
DOIT_TESTS_BUNDLE_ID = com.yourorg.doitTests
DOIT_UITESTS_BUNDLE_ID = com.yourorg.doitUITests
DOIT_WIDGET_BUNDLE_ID = com.yourorg.doit.doitActivityWidget
EOF
    echo "✅ Wrote $LOCAL_CONFIG"
    echo "   Supabase URL: $SUPABASE_URL"
else
    if [ -f "$LOCAL_CONFIG" ]; then
        echo "ℹ️  Local.xcconfig already exists — skipping."
    else
        echo "⚠️  DOIT_SUPABASE_URL and DOIT_SUPABASE_ANON_KEY not set."
        echo ""
        echo "   To set up your iOS config:"
        echo ""
        echo "   1. Copy the example:"
        echo "      cp $EXAMPLE_CONFIG $LOCAL_CONFIG"
        echo ""
        echo "   2. Edit $LOCAL_CONFIG and fill in:"
        echo "      - DOIT_SUPABASE_URL (your Supabase project URL)"
        echo "      - DOIT_SUPABASE_ANON_KEY (your Supabase anon/publishable key)"
        echo "      - DOIT_WAITLIST_URL (your waitlist URL)"
        echo "      - DOIT_DEVELOPMENT_TEAM (your Apple Team ID)"
        echo "      - DOIT_BUNDLE_ID (your app bundle ID)"
        echo ""
        exit 1
    fi
fi
